on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: '原镜像名称'
        required: true
        default: 'mysql/mysql-server'
      NEW_NAME:
        description: '同步后镜像名称'
        required: true
        default: 'mysql-server'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QYWX_ROBOT_URL: ${{ secrets.QYWX_ROBOT_URL }}
    steps:
      - name: ls
        run: |
          ls -l
          pwd
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Pull, tag, and push Docker image
        run: |
          docker pull --platform arm64 jenkins/jenkins:latest
          # docker tag ${{ github.event.inputs.IMAGE_NAME }}:${{ github.event.inputs.IMAGE_VERSION }} ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/${{ github.event.inputs.NEW_NAME }}:${{ github.event.inputs.IMAGE_VERSION }}
          # docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/${{ github.event.inputs.NEW_NAME }}:${{ github.event.inputs.IMAGE_VERSION }}