on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME: # ${{ github.event.inputs.IMAGE_NAME }}
        description: 'original image name'
        required: true
        default: 'centos/centos7' 
  push:
    branches:
      - main
         
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # docker pull IMAGE_NAME:IMAGE_TAG
      # docker push TARGET_REGISTRY/TARGET_REPOSITORY:IMAGE_TAG
      IMAGE_NAME: "kubesphere/kube-state-metrics" ##
      TARGET_REGISTRY: "registry.cn-hangzhou.aliyuncs.com"
      TARGET_REPOSITORY: "waterfalls/kube-state-metrics" ##
      IMAGE_TAG: "v2.5.0" ##
      ARCH: "arm64"
    steps:
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ env.TARGET_REGISTRY }}
      - name: Pull, tag, and push Docker image
        run: |
          docker pull --platform ${{ env.ARCH }} ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.TARGET_REGISTRY }}/${{ env.TARGET_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.TARGET_REGISTRY }}/${{ env.TARGET_REPOSITORY }}:${{ env.IMAGE_TAG }}